# No the best way to test but it works.
# Using REST CLIENT vscode extension to make requests

GET http://localhost:3000/api
# Response example 
# {"message": "Hello World"}
### <-- symbol for separating requests

POST http://localhost:3000/api/example/validation?test=123
Content-Type: application/json

{
    "str_test": "haha required string, otherwise it will throw an error",
    "email": "artiom@gmail.com"
}

# Response example
# {
#   "message": "Hello world",
#   "your_email": "artiom@gmail.com",
#   "query": "123"
# }



###

# Change the last route path to see how the dynamic route interacts
GET http://localhost:3000/api/example/lmaodynamicroutelolllll

# Response example
# {
#   "dynamic_route": "lmaodynamicroutelolllll"
# }


###

# Change the query "example" to "1", "2", "3" to see the their result!
GET http://localhost:3000/api/example/errors?example=1

# Response example
# {
#   "code": 400,
#   "errors": [
#     {
#       "status": 500,
#       "code": "SOME_ERROR_HAPPEND",
#       "message": "Here is a custom message"
#     }
#   ]
# }


###

POST http://localhost:3000/api/example/create-user
Content-Type: application/json

{
    "username": "artiomuwu"
}

# Response example
# {
#   "id": 1,
#   "username": "artiomuwu",
#   "created_at": "2024-03-14T21:41:48.687Z"
# }
#
# Another example
# {
#   "code": 409,
#   "errors": [
#     {
#       "status": 409,
#       "code": "UNIQUE_CONSTANT_VIOLATION",
#       "message": "Username already taken"
#     }
#   ]
# }